openapi: 3.0.0
info:
  title: Work Queue Manager API
  description: Servics to abstract the work queue manager
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /wqm/queues:
    get:
      summary: Get a list of all work queues
      description: Retrieve a list of all queue IDs and Names
      tags:
        - Work Queues
      parameters:
        - name: limit
          in: query
          description: The maximum number of queues to return
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Queue"
        "500":
          description: An internal server error
    post:
      summary: Create a new work queue
      description: Create a new work queue with the specified name and description
      tags:
        - Work Queues
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the new work queue
                  example: my-queue
                description:
                  type: string
                  description: A description of the new work queue
                  example: This is my new work queue
      responses:
        "201":
          description: The work queue was created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Queue"
        "400":
          description: The request was invalid
        "500":
          description: An internal server error
  /wqm/queues/{queue_id}:  
    put:
      summary: Update an existing work queue
      description: Update an existing work queue with the specified ID
      tags:
        - Work Queues
      parameters:
        - name: queue_id
          in: path
          description: The ID of the work queue to update
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The new name of the work queue
                  example: my-updated-queue
                description:
                  type: string
                  description: The new description of the work queue
                  example: This is my updated work queue
      responses:
        "200":
          description: The work queue was updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Queue"
        "400":
          description: The request was invalid
        "404":
          description: The work queue was not found
        "500":
          description: An internal server error
    delete:
      summary: Soft delete an existing work queue
      description: Soft delete an existing work queue with the specified ID
      tags:
        - Work Queues
      parameters:
        - name: queue_id
          in: path
          description: The ID of the work queue to delete
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: The work queue was deleted successfully
        "404":
          description: The work queue was not found
        "500":
          description: An internal server error

  /wqm/queues/{queue_id}/items:
    get:
      summary: Get a list of open work queue items
      description: Retrieve all open work queue item by queue ID
      tags:
        - Work Items
      parameters:
        - name: queue_id
          in: path
          description: The ID of the work queue
          required: true
          schema:
            type: integer
        - name: item_id
          in: query
          description: The ID of the work queue item
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QueueItem"
        "404":
          description: The work queue item was not found
        "500":
          description: An internal server error
  
    post:
      summary: Add a new work queue item on the specified queue
      description: Add a new work queue itemt on the specified queue by queue ID
      tags:
        - Work Items
      parameters:
        - name: queue_id
          in: path
          description: The ID of the work queue to add the item to
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the new queue item
                  example: my-new-queue-item
                description:
                  type: string
                  description: A description of the new queue item
                  example: This is my new work queue item
              required:
                - name
      responses:
        "201":
          description: The work queue item was added successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QueueItem"
        "400":
          description: The request was invalid
        "404":
          description: The work queue was not found
        "500":
          description: An internal server error
  /wqm/queues/{queue_id}/items/lock:
    get:
      summary: Get a list of locked work queue items
      description: Retrieve all locked work queue item by queue ID
      tags:
        - Work Items
      parameters:
        - name: queue_id
          in: path
          description: The ID of the work queue
          required: true
          schema:
            type: integer
        - name: item_id
          in: query
          description: The ID of the work queue item
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QueueItem"
        "404":
          description: The work queue item was not found
        "500":
          description: An internal server error

  /wqm/items/{item_id}:
    put:
      summary: Update an existing work queue item
      description: Update an existing work queue item with the specified item ID
      tags:
        - Work Items
      parameters:
        - name: queue_id
          in: path
          description: The ID of the work queue that the item belongs to
          required: true
          schema:
            type: integer
        - name: item_id
          in: query
          description: The ID of the work queue item to update
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The new name of the work queue item
                  example: my-updated-queue-item
                description:
                  type: string
                  description: The new description of the work queue item
                  example: This is my updated work queue item
              required:
                - name
      responses:
        "200":
          description: The work queue item was updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QueueItem"
        "400":
          description: The request was invalid
        "404":
          description: The work queue item was not found
        "500":
          description: An internal server error

    delete:
      summary: Soft delete an existing work queue item
      description: Soft delete an existing work queue item with the specified item ID
      tags:
        - Work Items
      parameters:
        - name: queue_id
          in: path
          description: The ID of the work queue that the item belongs to
          required: true
          schema:
            type: integer
        - name: item_id
          in: query
          description: The ID of the work queue item to delete
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: The work queue item was deleted successfully
        "404":
          description: The work queue item was not found
        "500":
          description: An internal server error

  /wqm/items/{item_id}/lock:
    put:
      summary: Toggle work queue item lock
      description: Toggle work queue item with the specified item ID
      tags:
        - Work Items
      parameters:
        - name: queue_id
          in: path
          description: The ID of the work queue that the item belongs to
          required: true
          schema:
            type: integer
        - name: item_id
          in: query
          description: The ID of the work queue item to update
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The new name of the work queue item
                  example: my-updated-queue-item
                description:
                  type: string
                  description: The new description of the work queue item
                  example: This is my updated work queue item
              required:
                - name
      responses:
        "200":
          description: The work queue item was updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QueueItem"
        "400":
          description: The request was invalid
        "404":
          description: The work queue item was not found
        "500":
          description: An internal server error

  /wqm/items/search:
    get:
      summary: Search for work items
      description: Search for work items by name or description
      tags:
        - Work Items
      parameters:
        - name: queue_id
          in: query
          description: The ID of the work queue to search in
          required: true
          schema:
            type: integer
        - name: search_query
          in: query
          description: The search query to use
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The search results were retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/QueueItem"
        "400":
          description: The request was invalid
        "500":
          description: An internal server error

components:
  schemas:
    Queue:
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier for the queue
          example: 1
        name:
          type: string
          description: The name of the queue
          example: my-queue
        description:
          type: string
          description: A description of the queue
          example: This is my new work queue
    QueueItem:
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier for the work queue item
          example: 1
        name:
          type: string
          description: The name of the work queue item
          example: my-work-item
        description:
          type: string
          description: A description of the work queue item
          example: This is my new work queue item
  
  