openapi: 3.0.0
info:
  title: Work Queue Manager API
  description: Servics to abstract the work queue manager
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
# Work Queues
  /wqm/queues:
    get:
      summary: Get a list of all work queues
      description: Retrieve a list of all queue IDs and Names
      tags:
        - Work Queues
      parameters:
        - name: per_page
          in: query
          description: The number of items per page
          required: false
          schema:
            type: integer
            minimum: 10
            maximum: 100
            default: 20
        - name: page
          in: query
          description: The number of the page
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 1
        - name: queue_type
          in: query
          description: The type of the queue (LIFO, FIFO, NONE)
          required: false
          schema:
            type: string
            enum:
              - LIFO
              - FIFO
              - NONE
        - name: status
          in: query
          description: Status of the queues (ACTIVE, DELETED)
          required: false
          schema:
            type: string
            enum:
              - ACTIVE
              - DELETED
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Queue"
        "500":
          description: An internal server error
    post:
      summary: Create a new work queue
      description: Create a new work queue with the specified name and description
      tags:
        - Work Queues
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the new work queue
                  example: a-queue
                description:
                  type: string
                  description: A description of the new work queue
                  example: This is my new work queue
                queue_type:
                  type: string
                  description: The type of the queue (LIFO, FIFO, NONE)
                  example: LIFO
                statue:
                  type: string
                  description: The status of the new work queue
                  example: ACTIVE
              required:
                - name
                - description
                - queue_type
                - status
      responses:
        "201":
          description: The work queue was created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Queue"
        "400":
          description: The request was invalid
        "500":
          description: An internal server error
  /wqm/queues/{queue_id}:  
    put:
      summary: Update an existing work queue
      description: Update an existing work queue with the specified ID
      tags:
        - Work Queues
      parameters:
        - name: queue_id
          in: path
          description: The ID of the work queue to update
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The new name of the work queue
                  example: an-updated-queue
                description:
                  type: string
                  description: The new description of the work queue
                  example: This is an updated work queue
                queue_type:
                  type: string
                  description: The type of the queue (LIFO, FIFO, NONE)
                  example: LIFO
                status: 
                  type: string
                  description: The new status of the work queue
                  example: ACTIVE
      responses:
        "200":
          description: The work queue was updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Queue"
        "400":
          description: The request was invalid
        "404":
          description: The work queue was not found
        "500":
          description: An internal server error
    delete:
      summary: Soft delete an existing work queue
      description: Soft delete an existing work queue with the specified ID
      tags:
        - Work Queues
      parameters:
        - name: queue_id
          in: path
          description: The ID of the work queue, changing status to DELETED
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: The work queue was deleted successfully
        "404":
          description: The work queue was not found
        "500":
          description: An internal server error
# Work Items
  /wqm/queues/{queue_id}/items:
    get:
      summary: Get a list of open work queue items
      description: Retrieve all open work queue item by queue ID
      tags:
        - Work Items
      parameters:
        - name: queue_id
          in: path
          description: The ID of the work queue
          required: true
          schema:
            type: integer
        - name: per_page
          in: query
          description: The number of items per page
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: page
          in: query
          description: The number of the page
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 1
        - name: status
          in: query
          description: Status of the work items (OPEN, LOCKED, PROCESSED, DELETED)
          required: true
          schema:
            type: string
            enum:
              - OPEN
              - LOCKED
              - PROCESSED
              - DELETED
        - name: lock
          in: query
          description: Lock work item(s) (LOCK)
          required: false
          schema:
            type: string
            enum:
              - LOCK
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WorkItem"
        "404":
          description: The work queue item was not found
        "500":
          description: An internal server error
    post:
      summary: Add a new work queue item on the specified queue
      description: Add a new work queue itemt on the specified queue by queue ID
      tags:
        - Work Items
      parameters:
        - name: queue_id
          in: path
          description: The ID of the work queue to add the item to
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the new queue item
                  example: a-new-queue-item
                description:
                  type: string
                  description: A description of the new queue item
                  example: This is a new work queue item
                status:
                  type: string
                  description: Work item status (OPEN, LOCKED, PROCESSED, DELETED)
                  example: OPEN
              required:
                - name
                - description
                - status
      responses:
        "201":
          description: The work queue item was added successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WorkItem"
        "400":
          description: The request was invalid
        "404":
          description: The work was not found
        "500":
          description: An internal server error
  /wqm/queues/{queue_id}/items/{item_id}:
    put:
      summary: Update an existing work queue item
      description: Update an existing work queue item with the specified item ID
      tags:
        - Work Items
      parameters:
        - name: queue_id
          in: path
          description: The ID of the work queue to update the item in
          required: true
          schema:
            type: integer
        - name: item_id
          in: path
          description: The ID of the work queue item to update
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The new name of the work queue item
                  example: updated-queue-item
                description:
                  type: string
                  description: The new description of the work queue item
                  example: This is my updated work queue item
                status:
                  type: string
                  description: Work item status (OPEN, LOCKED, PROCESSED, DELETED)
                  example: OPEN
              required:
                - status
      responses:
        "200":
          description: The work item was updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WorkItem"
        "400":
          description: The request was invalid
        "404":
          description: The work item was not found
        "500":
          description: An internal server error

    delete:
      summary: Soft delete an existing work queue item
      description: Soft delete an existing work queue item with the specified item ID
      tags:
        - Work Items
      parameters:
        - name: queue_id
          in: path
          description: The ID of the work queue to delete the item from
          required: true
          schema:
            type: integer
        - name: item_id
          in: path
          description: The ID of the work item to delete
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: The work item was deleted successfully
        "404":
          description: The work item was not found
        "500":
          description: An internal server error
# Search
  /wqm/search:
    get:
      summary: Search for work items
      description: Search for work items by name or description
      tags:
        - Search
      parameters:
        - name: queue_id
          in: query
          description: The ID of the work queue to search in
          required: false
          schema:
            type: integer
        - name: search_query
          in: query
          description: The search query to use
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The search results were retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/WorkItem"
        "400":
          description: The request was invalid
        "500":
          description: An internal server error
# Components
components:
  schemas:
    Queue:
      type: object
      properties:
        queue_id:
          type: integer
          description: The unique identifier for the queue
          example: 1
        name:
          type: string
          description: The name of the queue
          example: a-queue
        description:
          type: string
          description: A description of the queue
          example: This is a work queue
        queue_type:
          type: string
          description: The queue read order LIFO or FIFO or NONE
          example: FIFO
        status:
          type: string
          description: The status of the work queue
          example: ACTIVE

    WorkItem:
      type: object
      properties:
        item_id:
          type: integer
          description: The unique identifier for the work queue item
          example: 1
        name:
          type: string
          description: The name of the work item
          example: work-item
        description:
          type: string
          description: A description of the work item
          example: This is a work item 
        status:
          type: string
          description: The status of the work item
          example: OPEN

# Path: wqm.yaml
  
  
